# Generates FRENCH_REVIEW.md from the shipped Keyed and DefInjected XML, per TRANSLATIONS.md
# section 3 ("Systematic French review by Virginie"). Read-only: never edits French text.
# Re-run whenever a French or English file changes, and paste the revision it names into
# STATUS.md's Translation audit line.
$ErrorActionPreference = 'Stop'
$root = Split-Path -Parent $PSScriptRoot
$modRoot = Join-Path $root 'Mod'

function Read-Keyed($path) {
    if (-not (Test-Path $path)) { return @{} }
    [xml]$xml = Get-Content $path -Encoding UTF8
    $map = [ordered]@{}
    foreach ($node in $xml.LanguageData.ChildNodes) {
        if ($node.NodeType -ne 'Element') { continue }
        $map[$node.Name] = $node.InnerText
    }
    return $map
}

$revision = (git -C $root rev-parse --short HEAD 2>$null)
if (-not $revision) { $revision = '(uncommitted)' }

$enKeyed = Read-Keyed (Join-Path $modRoot 'Languages/English/Keyed/ContentedLivestock.xml')
$frKeyed = Read-Keyed (Join-Path $modRoot 'Languages/French/Keyed/ContentedLivestock.xml')

$enNeedDI = Read-Keyed (Join-Path $modRoot 'Languages/English/DefInjected/NeedDef/Needs_Contentment.xml')
$frNeedDI = Read-Keyed (Join-Path $modRoot 'Languages/French/DefInjected/NeedDef/Needs_Contentment.xml')
$needDef  = [xml](Get-Content (Join-Path $modRoot 'Defs/NeedDefs/Needs_Contentment.xml') -Encoding UTF8)

$enMainDI = Read-Keyed (Join-Path $modRoot 'Languages/English/DefInjected/MainButtonDef/MainButtons_ContentedLivestock.xml')
$frMainDI = Read-Keyed (Join-Path $modRoot 'Languages/French/DefInjected/MainButtonDef/MainButtons_ContentedLivestock.xml')
$mainDef  = [xml](Get-Content (Join-Path $modRoot 'Defs/MainButtonDefs/MainButtons_ContentedLivestock.xml') -Encoding UTF8)

function Escape-Cell($s) {
    if ($null -eq $s) { return '' }
    return ($s -replace '\|', '\|') -replace "`r?`n", '<br>'
}

$sb = New-Object System.Text.StringBuilder
[void]$sb.AppendLine("# French review")
[void]$sb.AppendLine()
[void]$sb.AppendLine("Generated by ``scripts/Generate-FrenchReview.ps1`` from revision ``$revision``. Original mod: no")
[void]$sb.AppendLine("source language other than English, so the Original column repeats English.")
[void]$sb.AppendLine()
[void]$sb.AppendLine("No text in this mod agrees with a pawn's gender (no ``{PAWN_gender ? ...}`` switch anywhere):")
[void]$sb.AppendLine("every string is settings UI, a tooltip or a need description, none of it addressed at a")
[void]$sb.AppendLine("specific animal's gender.")
[void]$sb.AppendLine()

[void]$sb.AppendLine("## Keyed/ContentedLivestock.xml")
[void]$sb.AppendLine()
[void]$sb.AppendLine("| Key or path | Original | English | French |")
[void]$sb.AppendLine("|---|---|---|---|")
foreach ($key in $frKeyed.Keys) {
    $en = $enKeyed[$key]
    $fr = $frKeyed[$key]
    [void]$sb.AppendLine("| $key | $(Escape-Cell $en) | $(Escape-Cell $en) | $(Escape-Cell $fr) |")
}
[void]$sb.AppendLine()

[void]$sb.AppendLine("## DefInjected/NeedDef/Needs_Contentment.xml")
[void]$sb.AppendLine()
[void]$sb.AppendLine("| Key or path | Original | English | French |")
[void]$sb.AppendLine("|---|---|---|---|")
foreach ($key in $frNeedDI.Keys) {
    $field = $key.Split('.')[-1]
    $en = if ($enNeedDI.Contains($key)) { $enNeedDI[$key] } else { $needDef.Defs.NeedDef.$field }
    $fr = $frNeedDI[$key]
    [void]$sb.AppendLine("| $key | $(Escape-Cell $en) | $(Escape-Cell $en) | $(Escape-Cell $fr) |")
}
[void]$sb.AppendLine()

[void]$sb.AppendLine("## DefInjected/MainButtonDef/MainButtons_ContentedLivestock.xml")
[void]$sb.AppendLine()
[void]$sb.AppendLine("| Key or path | Original | English | French |")
[void]$sb.AppendLine("|---|---|---|---|")
foreach ($key in $frMainDI.Keys) {
    $field = $key.Split('.')[-1]
    $en = if ($enMainDI.Contains($key)) { $enMainDI[$key] } else { $mainDef.Defs.MainButtonDef.$field }
    $fr = $frMainDI[$key]
    [void]$sb.AppendLine("| $key | $(Escape-Cell $en) | $(Escape-Cell $en) | $(Escape-Cell $fr) |")
}
[void]$sb.AppendLine()

[void]$sb.AppendLine("## Session-flagged rows")
[void]$sb.AppendLine()
[void]$sb.AppendLine("None: terminology, tone and grammar all read as straightforward technical French to the")
[void]$sb.AppendLine("session. No row carries a ``?`` column.")

$outPath = Join-Path $root 'FRENCH_REVIEW.md'
[System.IO.File]::WriteAllText($outPath, $sb.ToString(), (New-Object System.Text.UTF8Encoding($false)))
Write-Host "wrote $outPath"
